const LANG = {
ko: {
    site_title: "RSS 좀비탈출서버",
    site_subtitle: "FAQ / 명령어 목록",
    tab_faq: "1) 자주묻는 질문",
    tab_cmds: "2) 명령어 목록",
    faq_title: "자주묻는 질문",
    faq_hint: "질문을 누르면 답이 펼쳐집니다.",
    cmds_title: "명령어 목록",
    cmds_hint: "모든 명령어는 !와 / 둘 다 가능합니다.",
    cmds_user: "일반 사용자 명령어",
    cmds_vip: "후원자 전용 명령어",
    cmds_vip_note: "후원자 권한이 있는 유저만 사용할 수 있습니다.",
    th_cmd: "명령어",
    th_desc: "설명",
    th_example: "예시",
    last_update: "마지막 업데이트:",
    cmds_footer: "모든 명령어를 확인하려면 디스코드를 확인해주세요.",
    toggle: "열기/닫기",
    faq_1: "스토어 어떻게 사용하나요?",
    faq_2: "프레임이 너무 안 나와요 ㅠㅠ",
    faq_3: "소리가 너무 커요 ㅠㅠ",
    faq_4: "문의/신고는 어디로 하나요?",
    faq_5: "서버 규칙을 어디서 볼 수 있나요?",
    answer_1_1: "CS2에서 콘솔창을 열고",
    answer_1_2: "를 입력하세요.",
    answer_1_3: "또는 아래 명령어를 콘솔창에 입력해 단축키를 설정할 수도 있습니다.",
    answer_1_4: "하단의 오른쪽위의 복사하기를 누르고 콘솔창에 붙여넣기(Ctrl+V)로 명령어를 입력해주세요.",
    answer_2_1: "총소리를 끄거나 하이드를 쓰면 프레임이 올라갈 수 있습니다.",
    answer_2_2: "명령어를 사용해 보세요.",
    answer_3_1: "노래 소리가 너무 커요 :",
    answer_3_2: "콘솔창에 입력",
    answer_3_3: "다른 사람 총소리가 너무 커요 :",
    answer_3_4: "채팅창에 입력",
    discord_link: "디스코드 링크",
    answer_4: "로 들어와서 문의 및 신고 바랍니다.",
    answer_5: "로 들어와서 확인해주세요" ,
    cmd_1: "접속중인 어드민 목록",
    cmd_2: "춤, 감정표현 사용",
    cmd_3: "VIP 구매 링크 안내",
    cmd_4: "방탄복을 구매합니다.",
    cmd_5: "쿨다운인 맵 목록을 출력합니다",
    cmd_6: "화면 흔들림 효과를 제거합니다.",
    cmd_7: "맵 변경에 동의합니다.",
    cmd_8: "3인칭 <-> 1인칭 전환",
    cmd_vip_1: "내 캐릭터의 색깔을 정합니다.",
    cmd_vip_2: "채팅 태그를 설정합니다",
    cmd_vip_3: "채팅 태그의 색깔을 정합니다.",
    cmd_vip_4: "VIP 남은 기간을 확인합니다." ,
    faq_6: "콘솔은 어떻게 여나요?",
    answer_6_1: "콘솔은 (~, `) 키로 열 수 있습니다.",
    answer_6_2: "이때, 키를 게임 내에서 입력했는데도 불구하고 콘솔이 안 켜지면 아래 같은 가이드라인을 따라오세요.",
    answer_6_step1: "1. 설정",
    answer_6_step2: "2. 게임 클릭",
    answer_6_step3: "3. 게임 - 개발자 콘솔 사용(~) - 사용",
    answer_6_step4: "4. 게임 내에서 ~를 입력하여 아래 사진과 같은 콘솔창이 켜지면 성공"
  },

  en: {
    site_title: "RSS Zombie Escape Server",
    site_subtitle: "FAQ / Command List",
    tab_faq: "1) FAQ",
    tab_cmds: "2) Commands",
    faq_title: "Frequently Asked Questions",
    faq_hint: "Click a question to view the answer.",
    cmds_title: "Command List",
    cmds_hint: "All commands work with both ! and /",
    cmds_user: "General Commands",
    cmds_vip: "Donator (VIP) Commands",
    cmds_vip_note: "Only available to donators",
    th_cmd: "Command",
    th_desc: "Description",
    th_example: "Example",
    last_update: "Last updated:",
    cmds_footer: "For the full command list, please check Discord.",
    toggle: "Open / Close",
    faq_1: "How to use !store?",
    faq_2: "My FPS is very low",
    faq_3: "Too loud sound",
    faq_4: "How can i report or unban?",
    faq_5: "Where to see server rules?",
    answer_1_1: "In CS2, open the console and type",
    answer_1_2: ".",
    answer_1_3: "Alternatively, you can copy and paste the following commands in the console.",
    answer_1_4: "Click 'Copy' on the top right below, then paste (Ctrl+V) the commands into the console.",
    answer_2_1: "Disabling gun sounds or using hide can improve performance.",
    answer_2_2: "Try using the following commands.",
    answer_3_1: "Music volume is too loud:",
    answer_3_2: "Type this in the console",
    answer_3_3: "Other players' gun sounds are too loud:",
    answer_3_4: "Type this in chat",
    discord_link: "Discord link",
    answer_4: "and please submit your inquiries or reports.",
    answer_5: "and check the rules there." ,
    cmd_1: "List of online admins",
    cmd_2: "Use emotes or dance",
    cmd_3: "VIP purchase link info",
    cmd_4: "Purchase Kevlar armor.",
    cmd_5: "Display map cooldown list",
    cmd_6: "Remove screen shake effects.",
    cmd_7: "Vote to change the map (RTV).",
    cmd_8: "Toggle Between 3rd person & 1st person",
    cmd_vip_1: "Set your character color.",
    cmd_vip_2: "Set your chat tag.",
    cmd_vip_3: "Set your chat tag color.",
    cmd_vip_4: "Check remaining VIP duration.",
    faq_6: "How do I open the console?",
    answer_6_1: "You can open the console by pressing the (~, `) key.",
    answer_6_2: "If the console doesn't open even after pressing the key in-game, please follow the guidelines below.",
    answer_6_step1: "1. Settings",
    answer_6_step2: "2. Click Game",
    answer_6_step3: "3. Game -> Enable Developer Console (~) -> Yes",
    answer_6_step4: "4. Press ~ in-game, and if the console window appears like the picture below, you are successful!"
  },

  jp: {
    site_title: "RSS ゾンビエスケープサーバー",
    site_subtitle: "FAQ / コマンド一覧",
    tab_faq: "1) よくある質問",
    tab_cmds: "2) コマンド一覧",
    faq_title: "よくある質問",
    faq_hint: "質問をクリックすると回答が表示されます。",
    cmds_title: "コマンド一覧",
    cmds_hint: "すべてのコマンドは ! と / の両方が使用可能です。",
    cmds_user: "一般ユーザーコマンド",
    cmds_vip: "ドネーター（VIP）専用コマンド",
    cmds_vip_note: "ドネーター権限を持つユーザーのみ使用できます。",
    th_cmd: "コマンド",
    th_desc: "説明",
    th_example: "例",
    last_update: "最終更新日:",
    cmds_footer: "すべてのコマンドを確認するには、Discordをご確認ください。",
    toggle: "開く / 閉じる",
    faq_1: "ストアはどのように使用しますか？",
    faq_2: "フレームレート（FPS）が低すぎます(涙)",
    faq_3: "音が大きすぎます(涙)",
    faq_4: "お問い合わせや通報はどこでできますか？",
    faq_5: "サーバーのルールはどこで確認できますか？",
    answer_1_1: "CS2でコンソールを開き、",
    answer_1_2: "と入力してください。",
    answer_1_3: "または、以下のコマンドをコンソールに入力して、ショートカットキーを設定することもできます。",
    answer_1_4: "下部右上の「コピー」を押し、コンソールに貼り付け(Ctrl+V)してコマンドを入力してください。",
    answer_2_1: "銃声をオフにするか、ハイド（非表示）機能を使用するとFPSが向上する場合があります。",
    answer_2_2: "コマンドを試してみてください。",
    answer_3_1: "BGM（音楽）が大きすぎる場合 :",
    answer_3_2: "コンソールに入力",
    answer_3_3: "他人の銃声が大きすぎる場合 :",
    answer_3_4: "チャットに入力",
    discord_link: "Discordリンク",
    answer_4: "から参加し、お問い合わせや通報をお願いいたします。",
    answer_5: "から参加してご確認ください。" ,
    cmd_1: "接続中の管理者一覧",
    cmd_2: "ダンス、感情表現の使用",
    cmd_3: "VIP購入リンクの案内",
    cmd_4: "防弾チョッキを購入します。",
    cmd_5: "クールダウン中のマップ一覧を表示",
    cmd_6: "画面の揺れ効果を解除します。",
    cmd_7: "マップ変更に同意します（RTV）。",
    cmd_8: "3人視点 <-> 1人視点の切り替え",
    cmd_vip_1: "キャラクターの色を設定します。",
    cmd_vip_2: "チャットタグを設定します。",
    cmd_vip_3: "チャットタグの色を設定します。",
    cmd_vip_4: "VIPの残り期間を確認します。" ,
    faq_6: "コンソールはどのように開きますか？",
    answer_6_1: "コンソールは (~, `) キーで開くことができます。",
    answer_6_2: "ゲーム内でキーを押してもコンソールが開かない場合は、以下のガイドラインに従ってください。",
    answer_6_step1: "1. 設定",
    answer_6_step2: "2. 「ゲーム」をクリック",
    answer_6_step3: "3. ゲーム -> 開発者コンソールを有効にする(~) -> はい",
    answer_6_step4: "4. ゲーム内で ~ を入力し、下の写真のようにコンソール画面が表示されれば成功です！"
  },

  cn: {
    site_title: "RSS 僵尸 escape 服务器",
    site_subtitle: "FAQ / 指令列表",
    tab_faq: "1) 常见问题",
    tab_cmds: "2) 指令列表",
    faq_title: "常见问题",
    faq_hint: "点击问题可查看完整回答。",
    cmds_title: "指令列表",
    cmds_hint: "所有指令均支持使用 ! 和 / 前缀。",
    cmds_user: "普通玩家指令",
    cmds_vip: "赞助商（VIP）专属指令",
    cmds_vip_note: "仅限拥有赞助商权限的的玩家使用。",
    th_cmd: "指令",
    th_desc: "说明",
    th_example: "示例",
    last_update: "最后更新:",
    cmds_footer: "欲查看完整指令列表，请前往 Discord 确认。",
    toggle: "展开 / 收起",
    faq_1: "商店（!store）如何使用？",
    faq_2: "游戏帧率（FPS）太低了 ㅠㅠ",
    faq_3: "声音太大了 ㅠㅠ",
    faq_4: "咨询或举报应该去哪里？",
    faq_5: "在哪里可以查看服务器规则？",
    answer_1_1: "在 CS2 中打开控制台并输入",
    answer_1_2: "即可。",
    answer_1_3: "或者，您也可以将以下指令复制到控制台中，以设置菜单快捷键。",
    answer_1_4: "请点击下方右侧的“复制(복사하기)”，然后在控制台中粘贴(Ctrl+V)输入指令。",
    answer_2_1: "关闭枪声或使用玩家隐藏（!hide）功能可以有效提升帧率。",
    answer_2_2: "请尝试使用以下指令。",
    answer_3_1: "音乐声音太大时：",
    answer_3_2: "在控制台中输入",
    answer_3_3: "其他玩家的枪声太大时：",
    answer_3_4: "在聊天框中输入",
    discord_link: "Discord 链接",
    answer_4: "进行咨询或举报处理。",
    answer_5: "加入并在此进行确认。" ,
    cmd_1: "在线管理员列表",
    cmd_2: "使用跳舞或动作表情",
    cmd_3: "VIP 购买链接指引",
    cmd_4: "购买防弹衣。",
    cmd_5: "输出冷却中的地图列表",
    cmd_6: "移除画面震动效果。",
    cmd_7: "同意更换地图（RTV）。",
    cmd_8: "第三人称 <-> 第一人称切换",
    cmd_vip_1: "设置自定义角色颜色。",
    cmd_vip_2: "设置聊天称号/标签。",
    cmd_vip_3: "设置聊天标签的颜色。",
    cmd_vip_4: "检查 VIP 剩余有效天数。" ,
    faq_6: "如何打开控制台？",
    answer_6_1: "您可以通过按 (~, `) 键来打开控制台。",
    answer_6_2: "如果您在游戏中按了该键但控制台仍未打开，请按照以下指南进行操作。",
    answer_6_step1: "1. 设置",
    answer_6_step2: "2. 点击 游戏",
    answer_6_step3: "3. 游戏 -> 启用开发者控制台(~) -> 是",
    answer_6_step4: "4. 在游戏中按 ~ 键，如果出现如下图所示的控制台窗口，即表示成功！"
  }
};