const LANG = window.LANG = {
ko: {
    site_title: "RSS 좀비탈출서버",
    site_subtitle: "FAQ / 명령어 목록",
    tab_faq: "1) 자주묻는 질문",
    tab_cmds: "2) 명령어 목록",
    tab_guide: "3) 용어 사전",
    tab_news: "4) 공지",
    news_title: "공지",
    news_hint: "Discord 공지 채널의 최근 소식입니다.",
    news_loading: "공지를 불러오는 중...",
    news_empty: "등록된 공지가 없습니다.",
    news_open_discord: "Discord에서 보기",
    news_original: "원문 보기",
    global_search_label: "전체 검색",
    global_search_placeholder: "FAQ, 명령어, 용어, 공지 검색",
    global_search_hint: "검색어를 입력하면 FAQ, 명령어, 용어, 공지에서 찾아드립니다.",
    global_search_empty: "검색 결과가 없습니다.",
    global_search_summary: "FAQ {faq}개 · 명령어 {commands}개 · 용어 {terms}개 · 공지 {news}개",
    search_type_faq: "FAQ",
    search_type_command: "명령어",
    search_type_term: "용어",
    search_type_news: "공지",
    share_link: "링크 복사",
    share_done: "링크 복사됨",
    copy_done: "복사가 완료되었습니다.",
    report_issue: "잘못된 정보 제보",
    faq_title: "자주묻는 질문",
    faq_hint: "질문을 누르면 답이 펼쳐집니다.",
    cmds_title: "명령어 목록",
    cmds_hint: "모든 명령어는 !와 / 둘 다 가능합니다.",
    command_filter_all: "전체",
    command_favorites_only: "즐겨찾기만 보기",
    command_copy: "복사",
    command_copied: "복사됨",
    command_favorite_add: "즐겨찾기 추가",
    command_favorite_remove: "즐겨찾기 해제",
    command_result_count: "명령어 {count}개",
    command_empty: "조건에 맞는 명령어가 없습니다.",
    related_items: "관련 항목",
    quick_start_title: "처음이라면 여기부터",
    quick_start_description: "자주 쓰는 설정과 기본 안내만 먼저 확인해 보세요.",
    guide_title: "좀비탈출 용어 사전",
    guide_hint: "용어 또는 설명을 검색할 수 있습니다.",
    term_search_label: "용어 검색",
    term_search_placeholder: "용어 또는 설명 검색",
    term_loading: "용어를 불러오는 중...",
    term_empty: "검색 결과가 없습니다.",
    term_unavailable: "선택한 언어의 용어 사전은 준비 중입니다.",
    term_alias_label: "{term} 별칭 {count}개",
    cmds_user: "일반 사용자 명령어",
    cmds_vip: "후원자 전용 명령어",
    cmds_vip_note: "후원자 권한이 있는 유저만 사용할 수 있습니다.",
    th_cmd: "명령어",
    th_desc: "설명",
    th_example: "예시",
    last_update: "마지막 업데이트:",
    cmds_footer: "모든 명령어를 확인하려면 디스코드를 확인해주세요.",
    toggle: "열기/닫기",
    faq_1: "스토어 어떻게 사용하나요?",
    faq_2: "프레임이 너무 안 나와요 ㅠㅠ",
    faq_3: "소리가 너무 커요 ㅠㅠ",
    faq_4: "문의/신고는 어디로 하나요?",
    faq_5: "서버 규칙을 어디서 볼 수 있나요?",
    answer_1_1: "CS2에서 콘솔창을 열고",
    answer_1_2: "를 입력하세요.",
    answer_1_3: "또는 아래 명령어를 콘솔창에 입력해 단축키를 설정할 수도 있습니다.",
    answer_1_4: "하단의 오른쪽위의 복사하기를 누르고 콘솔창에 붙여넣기(Ctrl+V)로 명령어를 입력해주세요.",
    answer_2_1: "총소리를 끄거나 하이드를 쓰면 프레임이 올라갈 수 있습니다.",
    answer_2_2: "명령어를 사용해 보세요.",
    answer_3_1: "노래 소리가 너무 커요 :",
    answer_3_2: "콘솔창에 입력",
    answer_3_3: "다른 사람 총소리가 너무 커요 :",
    answer_3_4: "채팅창에 입력",
    discord_link: "디스코드 링크",
    answer_4: "로 들어와서 문의 및 신고 바랍니다.",
    answer_5: "로 들어와서 확인해주세요" ,
    cmd_1: "접속중인 어드민 목록",
    cmd_2: "춤, 감정표현 사용",
    cmd_3: "VIP 구매 링크 안내",
    cmd_4: "방탄복을 구매합니다.",
    cmd_5: "쿨다운인 맵 목록을 출력합니다",
    cmd_6: "화면 흔들림 효과를 제거합니다.",
    cmd_7: "맵 변경에 동의합니다.",
    cmd_8: "3인칭 <-> 1인칭 전환",
    cmd_vip_1: "내 캐릭터의 색깔을 정합니다.",
    cmd_vip_2: "채팅 태그를 설정합니다",
    cmd_vip_3: "채팅 태그의 색깔을 정합니다.",
    cmd_vip_4: "VIP 남은 기간을 확인합니다." ,
    faq_6: "콘솔은 어떻게 여나요?",
    answer_6_1: "콘솔은 (~, `) 키로 열 수 있습니다.",
    answer_6_2: "이때, 키를 게임내에서 입력했는데도 불구하고 콘솔이 안켜지면 아래와 같이 설정해주시면 됩니다.",
    answer_6_step1: "1. 설정",
    answer_6_step2: "2. 게임 클릭",
    answer_6_step3: "3. 게임 - 개발자 콘솔 사용(~) - 사용",
    answer_6_step4: "4. 게임 내에서 ~를 입력하여 아래 사진과 같은 콘솔창이 켜지면 성공"
  },

  en: {
    site_title: "RSS Zombie Escape Server",
    site_subtitle: "FAQ / Command List",
    tab_faq: "1) FAQ",
    tab_cmds: "2) Commands",
    tab_guide: "3) Glossary",
    tab_news: "4) News",
    news_title: "News",
    news_hint: "Recent announcements from the Discord channel.",
    news_loading: "Loading announcements...",
    news_empty: "No announcements yet.",
    news_open_discord: "View on Discord",
    news_original: "View original",
    global_search_label: "Search all",
    global_search_placeholder: "Search FAQ, commands, glossary, and news",
    global_search_hint: "Search FAQ, commands, glossary, and news.",
    global_search_empty: "No matching results.",
    global_search_summary: "FAQ {faq} · Commands {commands} · Terms {terms} · News {news}",
    search_type_faq: "FAQ",
    search_type_command: "Command",
    search_type_term: "Term",
    search_type_news: "News",
    share_link: "Copy link",
    share_done: "Link copied",
    copy_done: "Copied to clipboard.",
    report_issue: "Report incorrect information",
    faq_title: "Frequently Asked Questions",
    faq_hint: "Click a question to view the answer.",
    cmds_title: "Command List",
    cmds_hint: "All commands work with both ! and /",
    command_filter_all: "All",
    command_favorites_only: "Favorites only",
    command_copy: "Copy",
    command_copied: "Copied",
    command_favorite_add: "Add favorite",
    command_favorite_remove: "Remove favorite",
    command_result_count: "{count} commands",
    command_empty: "No matching commands.",
    related_items: "Related",
    quick_start_title: "New here? Start here",
    quick_start_description: "Check the essential settings and guides first.",
    guide_title: "Zombie Escape Glossary",
    guide_hint: "Glossary content for this language is being prepared.",
    term_search_label: "Search glossary",
    term_search_placeholder: "Search terms or descriptions",
    term_loading: "Loading glossary...",
    term_empty: "No matching terms.",
    term_unavailable: "The glossary for this language is not available yet.",
    term_alias_label: "{count} aliases for {term}",
    cmds_user: "General Commands",
    cmds_vip: "Donator (VIP) Commands",
    cmds_vip_note: "Only available to donators",
    th_cmd: "Command",
    th_desc: "Description",
    th_example: "Example",
    last_update: "Last updated:",
    cmds_footer: "For the full command list, please check Discord.",
    toggle: "Open / Close",
    faq_1: "How to use /store?",
    faq_2: "My FPS is very low",
    faq_3: "Too loud sound",
    faq_4: "How can i report or unban?",
    faq_5: "Where to see server rules?",
    answer_1_1: "In CS2, open the console and type",
    answer_1_2: ".",
    answer_1_3: "Alternatively, you can copy and paste the following commands in the console.",
    answer_1_4: "Click 'Copy' on the top right below, then paste (Ctrl+V) the commands into the console.",
    answer_2_1: "Disabling gun sounds or using hide can improve performance.",
    answer_2_2: "Try using the following commands.",
    answer_3_1: "Music volume is too loud:",
    answer_3_2: "Type this in the console",
    answer_3_3: "Other players' gun sounds are too loud:",
    answer_3_4: "Type this in chat",
    discord_link: "Discord link",
    answer_4: "and please submit your inquiries or reports.",
    answer_5: "and check the rules there." ,
    cmd_1: "List of online admins",
    cmd_2: "Use emotes or dance",
    cmd_3: "VIP purchase link info",
    cmd_4: "Purchase Kevlar armor.",
    cmd_5: "Display map cooldown list",
    cmd_6: "Remove screen shake effects.",
    cmd_7: "Vote to change the map (RTV).",
    cmd_8: "Toggle Between 3rd person & 1st person",
    cmd_vip_1: "Set your character color.",
    cmd_vip_2: "Set your chat tag.",
    cmd_vip_3: "Set your chat tag color.",
    cmd_vip_4: "Check remaining VIP duration.",
    faq_6: "How do I open the console?",
    answer_6_1: "You can open the console by pressing the (~, `) key.",
    answer_6_2: "If the console doesn't open even after pressing the key in-game, please follow the guidelines below.",
    answer_6_step1: "1. Settings",
    answer_6_step2: "2. Click Game",
    answer_6_step3: "3. Game -> Enable Developer Console (~) -> Yes",
    answer_6_step4: "4. Press ~ in-game, and if the console window appears like the picture below, you are successful!"
  },

  jp: {
    site_title: "RSS ゾンビエスケープサーバー",
    site_subtitle: "FAQ / コマンド一覧",
    tab_faq: "1) よくある質問",
    tab_cmds: "2) コマンド一覧",
    tab_guide: "3) 用語集",
    tab_news: "4) お知らせ",
    news_title: "お知らせ",
    news_hint: "Discordのお知らせチャンネルからの最新情報です。",
    news_loading: "お知らせを読み込んでいます...",
    news_empty: "お知らせはありません。",
    news_open_discord: "Discordで見る",
    news_original: "原文を見る",
    global_search_label: "全体検索",
    global_search_placeholder: "FAQ、コマンド、用語、お知らせを検索",
    global_search_hint: "FAQ、コマンド、用語、お知らせをまとめて検索します。",
    global_search_empty: "一致する結果がありません。",
    global_search_summary: "FAQ {faq}件 · コマンド {commands}件 · 用語 {terms}件 · お知らせ {news}件",
    search_type_faq: "FAQ",
    search_type_command: "コマンド",
    search_type_term: "用語",
    search_type_news: "お知らせ",
    share_link: "リンクをコピー",
    share_done: "リンクをコピーしました",
    copy_done: "クリップボードにコピーしました。",
    report_issue: "誤った情報を報告",
    faq_title: "よくある質問",
    faq_hint: "質問をクリックすると回答が表示されます。",
    cmds_title: "コマンド一覧",
    cmds_hint: "すべてのコマンドは ! と / の両方が使用可能です。",
    command_filter_all: "すべて",
    command_favorites_only: "お気に入りのみ",
    command_copy: "コピー",
    command_copied: "コピー済み",
    command_favorite_add: "お気に入りに追加",
    command_favorite_remove: "お気に入りを解除",
    command_result_count: "コマンド {count}件",
    command_empty: "一致するコマンドがありません。",
    related_items: "関連項目",
    quick_start_title: "初めての方はこちら",
    quick_start_description: "よく使う設定と基本案内を先に確認できます。",
    guide_title: "ゾンビエスケープ用語集",
    guide_hint: "この言語の用語集は準備中です。",
    term_search_label: "用語検索",
    term_search_placeholder: "用語または説明を検索",
    term_loading: "用語集を読み込み中...",
    term_empty: "一致する用語がありません。",
    term_unavailable: "選択した言語の用語集は準備中です。",
    term_alias_label: "{term}の別名 {count}件",
    cmds_user: "一般ユーザーコマンド",
    cmds_vip: "ドネーター（VIP）専用コマンド",
    cmds_vip_note: "ドネーター権限を持つユーザーのみ使用できます。",
    th_cmd: "コマンド",
    th_desc: "説明",
    th_example: "例",
    last_update: "最終更新日:",
    cmds_footer: "すべてのコマンドを確認するには、Discordをご確認ください。",
    toggle: "開く / 閉じる",
    faq_1: "ストアはどのように使用しますか？",
    faq_2: "フレームレート（FPS）が低すぎます(涙)",
    faq_3: "音が大きすぎます(涙)",
    faq_4: "お問い合わせや通報はどこでできますか？",
    faq_5: "サーバーのルールはどこで確認できますか？",
    answer_1_1: "CS2でコンソールを開き、",
    answer_1_2: "と入力してください。",
    answer_1_3: "または、以下のコマンドをコンソールに入力して、ショートカットキーを設定することもできます。",
    answer_1_4: "下部右上の「コピー」を押し、コンソールに貼り付け(Ctrl+V)してコマンドを入力してください。",
    answer_2_1: "銃声をオフにするか、ハイド（非表示）機能を使用するとFPSが向上する場合があります。",
    answer_2_2: "コマンドを試してみてください。",
    answer_3_1: "BGM（音楽）が大きすぎる場合 :",
    answer_3_2: "コンソールに入力",
    answer_3_3: "他人の銃声が大きすぎる場合 :",
    answer_3_4: "チャットに入力",
    discord_link: "Discordリンク",
    answer_4: "から参加し、お問い合わせや通報をお願いいたします。",
    answer_5: "から参加してご確認ください。" ,
    cmd_1: "接続中の管理者一覧",
    cmd_2: "ダンス、感情表現の使用",
    cmd_3: "VIP購入リンクの案内",
    cmd_4: "防弾チョッキを購入します。",
    cmd_5: "クールダウン中のマップ一覧を表示",
    cmd_6: "画面の揺れ効果を解除します。",
    cmd_7: "マップ変更に同意します（RTV）。",
    cmd_8: "3人視点 <-> 1人視点の切り替え",
    cmd_vip_1: "キャラクターの色を設定します。",
    cmd_vip_2: "チャットタグを設定します。",
    cmd_vip_3: "チャットタグの色を設定します。",
    cmd_vip_4: "VIPの残り期間を確認します。" ,
    faq_6: "コンソールはどのように開きますか？",
    answer_6_1: "コンソールは (~, `) キーで開くことができます。",
    answer_6_2: "ゲーム内でキーを押してもコンソールが開かない場合は、以下のガイドラインに従ってください。",
    answer_6_step1: "1. 設定",
    answer_6_step2: "2. 「ゲーム」をクリック",
    answer_6_step3: "3. ゲーム -> 開発者コンソールを有効にする(~) -> はい",
    answer_6_step4: "4. ゲーム内で ~ を入力し、下の写真のようにコンソール画面が表示されれば成功です！"
  }
};

