(() => {
  const english = {
    bp_season_badge: "SEASON 01 · UI DEMO",
    bp_days_left: "28 days remaining",
    bp_title: "RSS Battle Pass",
    bp_hint: "Earn pass XP through play and missions to unlock season rewards.",
    bp_current_progress: "Current progress",
    bp_next_reward: "Next reward",
    bp_stat_level: "Pass level",
    bp_stat_quests: "Missions completed",
    bp_stat_streak: "Play streak",
    bp_final_label: "FINAL REWARD",
    bp_final_name: "XXX Skin",
    bp_final_description: "The final reward for reaching level 20.",
    bp_quest_eyebrow: "MISSIONS",
    bp_quest_title: "Missions",
    bp_quest_hint: "Mission progress shown in this preview is sample data.",
    bp_daily: "Daily",
    bp_weekly: "Weekly",
    bp_complete: "Complete",
    bp_quest_rounds: "Play 3 rounds on any map",
    bp_quest_rounds_desc: "Stay with your team and finish each round.",
    bp_quest_infect: "Infect 15 humans as a zombie",
    bp_quest_infect_desc: "Help your team break through during infection rounds.",
    bp_quest_items: "Use map items 5 times",
    bp_quest_items_desc: "Use an item at the right moment.",
    bp_quest_wins: "Win 8 rounds",
    bp_quest_wins_desc: "Contribute to a round win as a human or zombie.",
    bp_quest_time: "Play for 180 minutes",
    bp_quest_time_desc: "Only active playtime is counted.",
    bp_quest_boss: "Deal 25,000 damage to bosses",
    bp_quest_boss_desc: "Focus priority targets and help your team clear the map.",
    bp_reward_eyebrow: "REWARD TRACK",
    bp_reward_title: "Level Rewards",
    bp_reward_hint: "Scroll horizontally to view rewards from levels 1–20.",
    bp_claimed: "Claimed",
    bp_current: "Current level",
    bp_locked: "Locked",
    bp_final_short: "XXX Skin",
    bp_final_reward: "Final reward",
    bp_mode_rewards: "Level Rewards",
    bp_mode_missions: "Missions",
    bp_pass_rank: "Pass Level",
    bp_pass_xp: "Pass XP",
    bp_weekly_xp: "Weekly XP",
    bp_nav_daily: "Daily Missions",
    bp_nav_weekly: "Weekly Missions",
    bp_nav_season: "Season Missions",
    bp_weekly_remaining: "4d 12h",
    bp_season_remaining: "28 days",
    bp_pass_reward: "Pass Reward",
    bp_loading_title: "Checking Steam sign-in...",
    bp_loading_description: "Loading Battle Pass progress.",
    bp_skip: "Skip to content",
    bp_language_label: "Language selection",
    bp_screen_label: "Battle Pass screen",
    bp_mission_filter_label: "Mission categories"
  };

  window.BATTLEPASS_LANG = {
    ko: {
      bp_season_badge: "SEASON 01 · UI DEMO",
      bp_days_left: "시즌 종료까지 28일",
      bp_title: "RSS 배틀 패스",
      bp_hint: "플레이와 임무로 패스 경험치를 모아 시즌 보상을 획득하세요.",
      bp_current_progress: "현재 진행도",
      bp_next_reward: "다음 보상",
      bp_stat_level: "패스 레벨",
      bp_stat_quests: "완료 임무",
      bp_stat_streak: "연속 플레이",
      bp_final_label: "FINAL REWARD",
      bp_final_name: "XXX 스킨",
      bp_final_description: "20레벨 달성 시 획득하는 최종 보상입니다.",
      bp_quest_eyebrow: "MISSIONS",
      bp_quest_title: "임무",
      bp_quest_hint: "시안의 임무 진행도는 예시 데이터입니다.",
      bp_daily: "일일",
      bp_weekly: "주간",
      bp_complete: "완료",
      bp_quest_rounds: "아무 맵에서 3라운드 플레이",
      bp_quest_rounds_desc: "팀과 함께 라운드를 끝까지 진행하세요.",
      bp_quest_infect: "좀비로 인간 15명 감염",
      bp_quest_infect_desc: "감염 라운드에서 팀의 돌파를 도우세요.",
      bp_quest_items: "맵 아이템 5회 사용",
      bp_quest_items_desc: "아이템을 적절한 순간에 사용하세요.",
      bp_quest_wins: "8라운드 승리",
      bp_quest_wins_desc: "인간 또는 좀비로 라운드 승리에 기여하세요.",
      bp_quest_time: "서버에서 180분 플레이",
      bp_quest_time_desc: "활성 플레이 시간만 누적됩니다.",
      bp_quest_boss: "보스에게 25,000 피해 주기",
      bp_quest_boss_desc: "우선 타겟을 공격해 팀의 클리어를 도우세요.",
      bp_reward_eyebrow: "REWARD TRACK",
      bp_reward_title: "레벨별 보상",
      bp_reward_hint: "가로로 이동해 1~20레벨 보상을 확인하세요.",
      bp_claimed: "수령 완료",
      bp_current: "현재 레벨",
      bp_locked: "잠김",
      bp_final_short: "XXX 스킨",
      bp_final_reward: "최종 보상",
      bp_mode_rewards: "레벨별 보상",
      bp_mode_missions: "임무",
      bp_pass_rank: "패스 등급",
      bp_pass_xp: "패스 경험치",
      bp_weekly_xp: "이번 주 경험치",
      bp_nav_daily: "금일 임무",
      bp_nav_weekly: "이번 주 임무",
      bp_nav_season: "이번 시즌 임무",
      bp_weekly_remaining: "4일 12시간",
      bp_season_remaining: "28일",
      bp_pass_reward: "패스 보상",
      bp_loading_title: "Steam 로그인 확인 중...",
      bp_loading_description: "배틀패스 진행도를 불러오고 있습니다.",
      bp_skip: "본문으로 건너뛰기",
      bp_language_label: "언어 선택",
      bp_screen_label: "배틀 패스 화면",
      bp_mission_filter_label: "임무 분류"
    },
    en: english,
    jp: { ...english }
  };
})();