window.BATTLEPASS_LANG = {
  "ko": {
    "bp_season_badge": "SEASON 01 · UI DEMO",
    "bp_days_left": "시즌 종료까지 28일",
    "bp_title": "RSS 배틀 패스",
    "bp_hint": "플레이와 퀘스트로 패스 경험치를 모아 시즌 한정 보상을 획득하세요.",
    "bp_current_progress": "현재 진행도",
    "bp_next_reward": "다음 보상",
    "bp_stat_level": "패스 레벨",
    "bp_stat_quests": "완료 퀘스트",
    "bp_stat_streak": "연속 플레이",
    "bp_final_label": "FINAL REWARD",
    "bp_final_name": "심연의 수호자 캐릭터 스킨",
    "bp_final_description": "20레벨 달성자만 획득하는 시즌 한정 전설 등급 보상",
    "bp_quest_eyebrow": "MISSIONS",
    "bp_quest_title": "시즌 퀘스트",
    "bp_quest_hint": "퀘스트 진행도는 화면 구성을 위한 예시입니다.",
    "bp_daily": "일일",
    "bp_weekly": "주간",
    "bp_complete": "완료",
    "bp_quest_rounds": "아무 맵에서 3라운드 플레이",
    "bp_quest_rounds_desc": "팀과 함께 라운드를 끝까지 진행하세요.",
    "bp_quest_infect": "좀비로 인간 15명 감염",
    "bp_quest_infect_desc": "감염 라운드에서 팀의 돌파를 도우세요.",
    "bp_quest_items": "맵 아이템 5회 사용",
    "bp_quest_items_desc": "아이템을 적절한 순간에 사용하세요.",
    "bp_quest_wins": "8라운드 승리",
    "bp_quest_wins_desc": "인간 또는 좀비로 라운드 승리에 기여하세요.",
    "bp_quest_time": "서버에서 180분 플레이",
    "bp_quest_time_desc": "플레이 시간은 라운드 참가 중에만 누적됩니다.",
    "bp_quest_boss": "보스에게 25,000 피해 주기",
    "bp_quest_boss_desc": "우선 타겟을 공격해 팀의 클리어를 도우세요.",
    "bp_reward_eyebrow": "REWARD TRACK",
    "bp_reward_title": "레벨별 보상",
    "bp_reward_hint": "가로로 이동해 1~20레벨 보상을 확인하세요.",
    "bp_claimed": "획득 완료",
    "bp_current": "현재 레벨",
    "bp_locked": "잠김",
    "bp_final_short": "심연의 수호자 스킨",
    "bp_final_reward": "최종 보상"
  },
  "en": {
    "bp_season_badge": "SEASON 01 · UI DEMO",
    "bp_days_left": "28 days remaining",
    "bp_title": "RSS Battle Pass",
    "bp_hint": "Earn pass XP through play and quests to unlock season-exclusive rewards.",
    "bp_current_progress": "Current progress",
    "bp_next_reward": "Next reward",
    "bp_stat_level": "Pass level",
    "bp_stat_quests": "Quests completed",
    "bp_stat_streak": "Play streak",
    "bp_final_label": "FINAL REWARD",
    "bp_final_name": "Abyss Warden Character Skin",
    "bp_final_description": "A season-exclusive legendary reward for reaching level 20.",
    "bp_quest_eyebrow": "MISSIONS",
    "bp_quest_title": "Season quests",
    "bp_quest_hint": "Quest progress is placeholder content for this UI demo.",
    "bp_daily": "Daily",
    "bp_weekly": "Weekly",
    "bp_complete": "Complete",
    "bp_quest_rounds": "Play 3 rounds on any map",
    "bp_quest_rounds_desc": "Stay with your team and finish each round.",
    "bp_quest_infect": "Infect 15 humans as a zombie",
    "bp_quest_infect_desc": "Help your team break through during infection rounds.",
    "bp_quest_items": "Use map items 5 times",
    "bp_quest_items_desc": "Use an item at the right moment.",
    "bp_quest_wins": "Win 8 rounds",
    "bp_quest_wins_desc": "Contribute to a round win as a human or zombie.",
    "bp_quest_time": "Play on the server for 180 minutes",
    "bp_quest_time_desc": "Time counts only while participating in a round.",
    "bp_quest_boss": "Deal 25,000 damage to bosses",
    "bp_quest_boss_desc": "Focus priority targets and help your team clear the map.",
    "bp_reward_eyebrow": "REWARD TRACK",
    "bp_reward_title": "Level rewards",
    "bp_reward_hint": "Scroll horizontally to view rewards from levels 1–20.",
    "bp_claimed": "Claimed",
    "bp_current": "Current level",
    "bp_locked": "Locked",
    "bp_final_short": "Abyss Warden Skin",
    "bp_final_reward": "Final reward"
  },
  "jp": {
    "bp_season_badge": "SEASON 01 · UI DEMO",
    "bp_days_left": "シーズン終了まで28日",
    "bp_title": "RSS バトルパス",
    "bp_hint": "プレイとクエストでパスXPを集め、シーズン限定報酬を獲得しましょう。",
    "bp_current_progress": "現在の進行度",
    "bp_next_reward": "次の報酬",
    "bp_stat_level": "パスレベル",
    "bp_stat_quests": "完了クエスト",
    "bp_stat_streak": "連続プレイ",
    "bp_final_label": "FINAL REWARD",
    "bp_final_name": "深淵の守護者キャラクタースキン",
    "bp_final_description": "レベル20到達者だけが獲得できるシーズン限定のレジェンダリー報酬。",
    "bp_quest_eyebrow": "MISSIONS",
    "bp_quest_title": "シーズンクエスト",
    "bp_quest_hint": "クエスト進行度はUIデモ用の仮データです。",
    "bp_daily": "デイリー",
    "bp_weekly": "ウィークリー",
    "bp_complete": "完了",
    "bp_quest_rounds": "任意のマップで3ラウンドプレイ",
    "bp_quest_rounds_desc": "チームと一緒にラウンドを最後まで進めましょう。",
    "bp_quest_infect": "ゾンビとして人間を15人感染",
    "bp_quest_infect_desc": "感染ラウンドでチームの突破を助けましょう。",
    "bp_quest_items": "マップアイテムを5回使用",
    "bp_quest_items_desc": "適切なタイミングでアイテムを使いましょう。",
    "bp_quest_wins": "8ラウンド勝利",
    "bp_quest_wins_desc": "人間またはゾンビとして勝利に貢献しましょう。",
    "bp_quest_time": "サーバーで180分プレイ",
    "bp_quest_time_desc": "プレイ時間はラウンド参加中のみ加算されます。",
    "bp_quest_boss": "ボスに25,000ダメージを与える",
    "bp_quest_boss_desc": "優先ターゲットを攻撃し、攻略に貢献しましょう。",
    "bp_reward_eyebrow": "REWARD TRACK",
    "bp_reward_title": "レベル報酬",
    "bp_reward_hint": "横にスクロールしてレベル1～20の報酬を確認できます。",
    "bp_claimed": "獲得済み",
    "bp_current": "現在のレベル",
    "bp_locked": "ロック中",
    "bp_final_short": "深淵の守護者スキン",
    "bp_final_reward": "最終報酬"
  }
};
